-- Copy and paste this into the Supabase SQL Editor to create the table

CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    pm1_0 NUMERIC,
    pm2_5 NUMERIC,
    pm10 NUMERIC,
    co2 INTEGER,
    temperature NUMERIC,
    humidity NUMERIC,
    aqi INTEGER,
    lat NUMERIC DEFAULT 16.0544,
    lng NUMERIC DEFAULT 108.2022,
    station_name TEXT DEFAULT 'Trạm Đà Nẵng – Hải Châu'
);

-- =========================================================================
-- NẾU BẠN ĐÃ CÓ SẴN BẢNG TỪ TRƯỚC VÀ CHỈ MUỐN THÊM CỘT VỊ TRÍ, DÙNG LỆNH SAU:
-- =========================================================================
-- ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS lat NUMERIC DEFAULT 16.0544;
-- ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS lng NUMERIC DEFAULT 108.2022;
-- ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS station_name TEXT DEFAULT 'Trạm Đà Nẵng – Hải Châu';
-- =========================================================================

-- Turn on Row Level Security (RLS) but allow anonymous inserting and reading for now
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON public.sensor_readings
FOR SELECT USING (true);

CREATE POLICY "Allow public insert access" 
ON public.sensor_readings
FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update access" 
ON public.sensor_readings
FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Allow public delete access" 
ON public.sensor_readings
FOR DELETE USING (true);

